### PR TITLE
Add devise

### PR DESCRIPTION
**Pull request by Stanleeeeee**
## In this pull request, my partner and I implemented the following:

- Removed current_user method in ApplicationController, devise will provide us with one.
[Installed and setup devise](https://github.com/heartcombo/devise#getting-started).
- Can register a new user.
- User logs in with a combination of email and password.
- Hashed passwords should be stored in the database.
- Ask for confirmation of email.
- Can reset password

### CODE REVIEW

**Review by descholar-ceo — APPROVED** [review]
Hi @Stanleeeeee && @Richez003 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all requirements ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by GzimAsani — CHANGES_REQUESTED** [review]
**Hi TEAM,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been already reviewed
 To solve this issue, kindly use your partner's link to ask for a review. you guys need to implement the requirement in both repos.
 [Read this part of the project requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=You%20should%20implement%20the%20above%20requirements%20in%20all%20repositories%20in%20your%20pair%2Dprogramming%20group.%20That%20means%20that%20each%20group%20member%20needs%20to%20open%20a%20new%20pull%20request%20in%20their%20repo.).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Stanleeeeee** [comment]
@GzimAsani the project has been approved but only my partner's link in the dashboard was marked to submit while my link is still showing Request Review. Kindly enable my submit link too.

**Comment by GzimAsani** [comment]
> @GzimAsani the project has been approved but only my partner's link in the dashboard was marked to submit while my link is still showing Request Review. Kindly enable my submit link too.

To solve this issue, kindly use your partner's link to ask for a review. you guys need to implement the requirement in both repos.
[Read this part of the project requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=You%20should%20implement%20the%20above%20requirements%20in%20all%20repositories%20in%20your%20pair%2Dprogramming%20group.%20That%20means%20that%20each%20group%20member%20needs%20to%20open%20a%20new%20pull%20request%20in%20their%20repo.).

**Comment by Stanleeeeee** [comment]
@GzimAsani This is the repo we use for the project. And it has been approved already. We didn't use any repo.

**Comment by GzimAsani** [comment]
> @GzimAsani This is the repo we use for the project. And it has been approved already. We didn't use any repo.


@Stanleeeeee Both of you should've submitted individual work(You your own repo and your collegue his own repo) and still both of you needed to have involvment(commits, pair-programming) on each others work. Kindly refer to this [Document](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=You%20should%20implement%20the%20above%20requirements%20in%20all%20repositories%20in%20your%20pair%2Dprogramming%20group.%20That%20means%20that%20each%20group%20member%20needs%20to%20open%20a%20new%20pull%20request%20in%20their%20repo.).

**Pull request merged**
